name: goreleaser

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # 获取完整的 git 历史，用于生成 changelog
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - uses: sigstore/cosign-installer@v3.10.0
      - uses: anchore/sbom-action/download-syft@v0.15.1
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'  # 使用 v2.x 的最新版本
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN}}

      - name: Publish rpm to Gemfury
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          for filename in dist/vfox*.{rpm,deb}; do
            curl -F package=@"$filename" https://{$FURY_TOKEN}@push.fury.io/versionfox/
          done